#!/usr/bin/env python3
"""D2 gate: coords.txt → verified transform → PLY.

Two worlds: Python owns file IO (trusted); Ontic owns the verified math
(synthesized + sieved). The kernel is called via ctypes with zero-copy
numpy data through the Flat-MemRef ABI.
"""
import sys, os, json, ctypes
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault("ONTIC_BIN", "ontic")
os.environ.setdefault("ONTIC_VAULT", ".ontic/vault")

VAULT = os.environ.get("ONTIC_VAULT", ".ontic/vault")
ONTIC = os.environ.get("ONTIC_BIN", "ontic")


class MemRefF64(ctypes.Structure):
    _fields_ = [
        ("allocated", ctypes.c_void_p),
        ("aligned", ctypes.c_void_p),
        ("offset", ctypes.c_long),
        ("size", ctypes.c_long),
        ("stride", ctypes.c_long),
    ]


def read_coords(path):
    vals = []
    for line in open(path):
        parts = line.strip().split()
        if len(parts) == 3:
            vals.extend(float(v) for v in parts)
    return np.array(vals, dtype=np.float64)


def call_list_kernel(so_path: str, symbol: str, pts: np.ndarray,
                     *scalar_vals: float) -> np.ndarray:
    """Call a List<F64>→List<F64> kernel natively. Zero-copy input."""
    lib = ctypes.CDLL(so_path)
    fn = getattr(lib, symbol)
    fn.restype = MemRefF64
    fn.argtypes = (
        [ctypes.c_void_p, ctypes.c_void_p,
         ctypes.c_long, ctypes.c_long, ctypes.c_long]
        + [ctypes.c_double] * len(scalar_vals)
    )
    arr = np.ascontiguousarray(pts, dtype=np.float64)
    ptr = arr.ctypes.data_as(ctypes.c_void_p)
    args = [ptr, ptr, 0, len(arr), 1] + list(scalar_vals)
    result = fn(*args)
    if result.size == 0 or not result.aligned:
        return np.array([], dtype=np.float64)
    buf = (ctypes.c_double * result.size).from_address(result.aligned)
    return np.frombuffer(buf, dtype=np.float64).copy()


def write_ply(path, points_flat):
    n = len(points_flat) // 3
    with open(path, "w") as f:
        f.write("ply\nformat ascii 1.0\n")
        f.write("comment generated by Ontic verified kernel\n")
        f.write(f"element vertex {n}\n")
        f.write("property float x\nproperty float y\nproperty float z\n")
        f.write("end_header\n")
        for i in range(n):
            f.write(f"{points_flat[i*3]:.6f} {points_flat[i*3+1]:.6f} {points_flat[i*3+2]:.6f}\n")


def main():
    coords_path = sys.argv[1] if len(sys.argv) > 1 else "examples/coords.txt"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "/tmp/opencode/output.ply"
    scale, offset = 0.5, 100.0

    # 1. Read input (trusted IO world).
    pts = read_coords(coords_path)
    print(f"read {len(pts)//3} points from {coords_path}")

    # 2. Find the vaulted translate_scale kernel.
    so_path = os.path.join(VAULT, "libtranslate_scale-b1ba4e69.so")
    if not os.path.exists(so_path):
        print("ERROR: solve transform.ont first:")
        print("  ontic solve examples/transform.ont --hand <candidate>")
        sys.exit(1)

    # 3. Call the verified kernel natively (zero-copy numpy).
    result = call_list_kernel(so_path, "translate_scale", pts,
                              scale / 2.0 * 2.0, offset)  # s=1 effectively... no
    # Actually just use scale directly since spec is wrapping tier.
    result = call_list_kernel(so_path, "translate_scale", pts, scale, offset)
    print(f"kernel returned {len(result)} values ({len(result)//3} vertices)")

    # 4. Write output (trusted IO world).
    write_ply(out_path, result)
    print(f"wrote {out_path}")

    # 5. Validate PLY header.
    header = open(out_path).read(200)
    assert "ply" in header and "element vertex" in header
    print(f"D2-GATE PASS ({len(result)//3} verified vertices)")


if __name__ == "__main__":
    main()
